name: Snyk Code Scanning

on: [workflow_dispatch]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Needed to upload SARIF

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        with:
          snyk-version: 'latest'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk and output SARIF
        continue-on-error: true
        run: |
          snyk test --all-projects --sarif-file-output=snyk-results.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-results.sarif
      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sarif-report
          path: snyk-results.sarif
